import JSBI from "jsbi";
import dynamic from "next/dynamic";
import Head from "next/head";
import type { FC, MouseEvent } from "react";
import { useCallback, useContext, useEffect, useRef, useState } from "react";
import { SkeletonTheme } from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import colors from "../colors";
import BasicErrorBoundary from "../components/BasicErrorBoundary";
import HeaderGlow from "../components/HeaderGlow";
import MainTitle from "../components/MainTitle";
import { WEI_PER_ETH } from "../eth-units";
import { FeatureFlagsContext, useFeatureFlags } from "../feature-flags";
import { formatZeroDecimals } from "../format";
import ContactSection from "../sections/ContactSection";
import type { TimeFrame } from "./time-frames";
import { getNextTimeFrame } from "./time-frames";
import FaqBlock from "./components/Faq";
