name: Build React TypeScript Project

on:
  push:
    branches:
      - master # Triggers on push to the master branch
  pull_request:
    branches:
      - "*" # Trigger on any pull request to any branch (including master)
    types:
      - opened # Trigger when a PR is opened
      - synchronize # Trigger when a PR is updated (committed to)
      - reopened # Trigger when a PR is reopened
      - closed # Trigger when a PR is closed (merged or just closed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          yarn install

      - name: Build the project
        run: |
          yarn build

      - name: Run tests
        run: |
          yarn test --ci --runInBand

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: .
