name: Build React TypeScript Project

on:
  push:
    branches:
      - master # Triggers on push to the master branch
  pull_request:
    types:
      - closed # Triggers when a PR is closed (merged or just closed)
    branches:
      - master # Only triggers for pull requests that target the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          yarn install

      - name: Build the project
        run: |
          yarn build  # Make sure you have a build script in your package.json

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: ./build
